repos:
  - repo: local
    hooks:
      - id: fmt
        name: Format Rust code
        entry: cargo fmt
        language: system
        types: [rust]
        args: ['--', '--check']
      - id: clippy
        name: Rust Clippy
        entry: cargo clippy
        language: system
        types: [rust]
        args: ['--', -W, clippy::all, -D, warnings]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
